---

- hosts: all
  become: true
  task:

  - name: Install apache and php for Rocky servers
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install apache and php for Mint servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Mint"   
