---

- hosts: all
  become: true
  tasks:
  

  - name: install apache and htop package
    package: 
      name: 
       - "{{ apache_package }}"
       - "{{ htop_package }}"
      state: latest
      update_cache: yes
