---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    dnf:
      update_cache: yes  

  - name: install httpd package
    dnf: 
      name: httpd
      state: absent

  - name: Install htop package
    dnf:
      name: htop
      state: absent
